### PR TITLE
Expose content fields

### PR DESCRIPTION
**Pull request by bartdegoede**
Include additional fields
==================
Currently, not all fields available in the Elasticsearch index are exposed through the REST API. Some for good reasons (such as the `combined_index_data` field, which is purely stored for backup-and-restore purposes, and not interesting for users), whereas others might be useful for users interested in **all** the textual content of a record, for instance as a source for data analysis.

This pull requests enables the API user to request the inclusion of additional fields (`all_text`, which contains all the text used for search in the search endpoints, or `source_data`, which is the original content representation of the record).

### CODE REVIEW

**Comment by breyten** [comment]
Sorry for the delay. Something with the holidays ;) Seems the way to go to me.

The tests work! Hurray! :+1: 

Why would there be a need to generate data if we have the static documents already? Or do you mean as an extra step?

**Comment by bartdegoede** [comment]
Because we need some way to find out whether data changes at the content source (when someone decides to rename an `ID` field to `identifier` for instance), but I'm not really sure how to proceed with that anyway :-)

**Comment by bartdegoede** [comment]
Maybe this is not the right place to have this discussion though :-) If you don't have other remarks, could you please merge this pull request? I'm not sure, but it seems something went wrong somewhere, as I can't seem to merge it myself.. Perhaps I should create another pull request? That just seems weird..

**Comment by bartdegoede** [comment]
I'm reopening this pull request.

**Comment by breyten** [comment]
I'm looking at this, so please hold :P

**Comment by bartdegoede** [comment]
I think I've resolved the merge disasters in #83, so I think we should merge that one, when you finished checking :-)

**Comment by breyten** [comment]
This is not good. I just merged this into dev.

**Comment by breyten** [comment]
Can you check if things are the way they're supposed to be? I had an issue where in the ocd_frontend tests it was using the wrong module.  (See 6fe3e3565f76f373605ccef17ff9603b98d6b0a3 )

**Comment by bartdegoede** [comment]
This is fixed now, and merged manually into `dev`. I'm modifying the CONTRIBUTING guidelines to make sure this won't happen again in the future.

**Pull request closed without merging**
